-- Задача 1. Като използвате SQL създайте таблици по дадените релационни схеми
-- Teams( tname: string, ocolor: string, rcolor: string, capitan: string)
-- Players ( pname: string, birthdate: date, tname: string )

SET SCHEMA DB2ADMIN;


CREATE TABLE TEAMS(
    TNAME CHAR(50) NOT NULL PRIMARY KEY,
    OCOLOR VARCHAR(10) NOT NULL,
    RCOLOR VARCHAR(10) NOT NULL,
    CAPITAN VARCHAR(50) -- NAME OF PLAYER
);

CREATE TABLE PLAYERS(
    PNAME CHAR(50) NOT NULL PRIMARY KEY,
    BIRTHDATE DATE,
    TNAME CHAR(50) NOT NULL -- NAME OF TEAM
);


ALTER TABLE TEAMS
ADD CONSTRAINT FK_TEAMS_PLAYERS
FOREIGN KEY(CAPITAN) REFERENCES PLAYERS(PNAME);

ALTER TABLE PLAYERS
ADD CONSTRAINT FK_PLAYERS_TEAMS
FOREIGN KEY(TNAME) REFERENCES TEAMS(TNAME);


ALTER TABLE PLAYERS
DROP CONSTRAINT FK_PLAYERS_TEAMS;

ALTER TABLE PLAYERS
ADD CONSTRAINT FK_PLAYERS_TEAMS
FOREIGN KEY(TNAME) REFERENCES TEAMS(TNAME)
ON UPDATE NO ACTION
ON DELETE CASCADE;

ALTER TABLE TEST
ADD CONSTRAINT CK_TEST_GENDER CHECK(GENDER IN (0,1));

DELETE FROM TEST WHERE ID = 2;

UPDATE TEST
SET NAME = 'IVANA'
WHERE ID = 1;

INSERT INTO TEST (ID, NAME, GENDER)
VALUES (3, 'GAGA1', 1),
       (4, 'GAGA2', 1),
       (5, 'GAGA3', 1),
       (6, 'GAGA4', 1),
       (7, 'GAGA5', 1);



-- Задача 2.  Като използвате SQL създайте таблици по дадените релационни схеми
-- Projects( projno: string, projname: string, location: string )
-- Departments ( deptno: string, deptname: string, mgrno: string )
-- Staff ( staffno: string, staffname: string, birthdate: date, salary: decimal, deptno: string, chiefno: string )
-- Projact( projno: string, staffno: string, prstdate: date, prendate: date)


CREATE TABLE PROJECTS(
    PROJNO CHAR(5) NOT NULL PRIMARY KEY,
    PROJNAME VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(20)
);


CREATE TABLE DEPT (
    DEPTNO CHAR(3) NOT NULL PRIMARY KEY,
    DEPTNAME VARCHAR(50) NOT NULL,
    MGRNO CHAR(6)
);


CREATE TABLE STAFF (
    STAFFNO CHAR(6) NOT NULL PRIMARY KEY,
    STAFFNAME VARCHAR(50) NOT NULL,
    BIRTHDATE DATE,
    SALARY DECIMAL(9,2),
    DEPTNO CHAR(3) NOT NULL REFERENCES DEPT(DEPTNO),
    CHIEFNO CHAR(6) REFERENCES STAFF(STAFFNO)
);

CREATE TABLE PROJACT(
    STAFFNO CHAR(6) NOT NULL,
    PROJNO CHAR(5) NOT NULL,
    PRSTDATE DATE,
    PRENDATE DATE,
    CONSTRAINT CK_PROJACT_DATE CHECK(PRSTDATE < PRENDATE),
    CONSTRAINT PK_PROJACT PRIMARY KEY (STAFFNO, PROJNO),
    CONSTRAINT FK_PROJACT_STAFF FOREIGN KEY(STAFFNO) REFERENCES STAFF(STAFFNO),
    CONSTRAINT FK_PROJACT_PROJECT FOREIGN KEY(PROJNO) REFERENCES PROJECTS(PROJNO)
);

ALTER TABLE DEPT
ADD CONSTRAINT FK_DEPT_STAFF
FOREIGN KEY (MGRNO) REFERENCES STAFF(STAFFNO);